// Manhattan happy hour deals data
const happyHourDeals = [
  // Midtown
  {
    id: 1,
    name: "The Friki Tiki",
    neighborhood: "midtown",
    subNeighborhood: "Midtown",
    address: "357 W 44th St, New York, NY 10036",
    location: [40.7596, -73.9911],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$10 frozen drinks; $9 wine; $6 beer",
    description: "Tropical tiki bar with island-inspired cocktails",
    website: "https://www.frikitiki.com/"
  },
  {
    id: 2,
    name: "Valerie",
    neighborhood: "midtown",
    subNeighborhood: "Midtown",
    address: "45 W 45th St, New York, NY 10036",
    location: [40.7567, -73.9812],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], 
    hours: "Happy Hour Daily",
    deals: "$12 cocktails; $9 select wines; $7 select beers; $1 oysters; $16 charcuterie board",
    description: "Art deco cocktail bar with upscale ambiance",
    website: "https://www.valerienyc.com/"
  },
  {
    id: 3,
    name: "The Stag's Head",
    neighborhood: "midtown",
    subNeighborhood: "Midtown",
    address: "252 E 51st St, New York, NY 10022",
    location: [40.7551, -73.9693],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$5 select beers; $6 well drinks; $7 select wines",
    description: "Craft beer bar with rustic charm",
    website: "https://www.stagheadsnyc.com/"
  },
  {
    id: 4,
    name: "Draught 55",
    neighborhood: "midtown",
    subNeighborhood: "Midtown",
    address: "245 E 55th St, New York, NY 10022",
    location: [40.7593, -73.9660],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$9 select cocktails; $5 beer; $6 well drinks; $2 off wine",
    description: "Cozy pub with extensive draft beer selection",
    website: "https://www.draught55.com/"
  },
  {
    id: 5,
    name: "The Rum House",
    neighborhood: "midtown",
    subNeighborhood: "Times Square",
    address: "228 W 47th St, New York, NY 10036",
    location: [40.7593, -73.9858],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$10 classic cocktails; $8 select wines; $6 beers",
    description: "Classic piano bar in The Edison Hotel specializing in rum",
    website: "https://www.therumhousenyc.com/"
  },
  {
    id: 6,
    name: "The Horny Ram",
    neighborhood: "midtown",
    subNeighborhood: "Midtown East",
    address: "951 2nd Ave, New York, NY 10022",
    location: [40.7541, -73.9707],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$8 Aperol spritz, mules, and select wines; $6 beers; 2 bites for $16",
    description: "Modern gastropub with two floors and rooftop seating",
    website: "https://www.thehornyram.com/"
  },
  {
    id: 7,
    name: "Castell Rooftop Lounge",
    neighborhood: "midtown",
    subNeighborhood: "Midtown",
    address: "260 W 40th St, New York, NY 10018",
    location: [40.7559, -73.9915],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$10 select cocktails; $8 wines; $7 beers",
    description: "Stylish rooftop lounge with city views",
    website: "https://www.castellnyc.com/"
  },
  {
    id: 8,
    name: "Industry Bar",
    neighborhood: "midtown",
    subNeighborhood: "Hell's Kitchen",
    address: "355 W 52nd St, New York, NY 10019",
    location: [40.7640, -73.9867],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$5 well drinks; $4 beers",
    description: "Popular LGBTQ+ bar with video screens and dancing",
    website: "http://www.industry-bar.com/"
  },
  {
    id: 9,
    name: "The Perfect Pint",
    neighborhood: "midtown",
    subNeighborhood: "Midtown",
    address: "123 W 45th St, New York, NY 10036",
    location: [40.7574, -73.9843],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$5 select pints; $6 house wines; $7 well drinks",
    description: "Irish pub with rooftop beer garden and extensive beer selection",
    website: "https://www.theperfectpintnyc.com/"
  },
  
  // West Village
  {
    id: 10,
    name: "The Spaniard",
    neighborhood: "west_village",
    subNeighborhood: "West Village",
    address: "190 West 4th Street, NY 10014",
    location: [40.7340, -74.0030],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 6:00 PM",
    deals: "'Little Spaniard' Single Smash Burger – $9, $2 off all draft beers",
    description: "Lively gastropub with vintage charm and extensive whiskey selection",
    website: "https://thespaniardnyc.com/"
  },
  {
    id: 11,
    name: "Hudson Hound",
    neighborhood: "west_village",
    subNeighborhood: "West Village",
    address: "575 Hudson Street, NY 10014",
    location: [40.7340, -74.0061],
    days: ["tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 6:00 PM",
    deals: "All Draught Beer – $7, Aperol Spritz/Margarita/Sangria – $10, 25% Off Wine, Bucket of 4 Beers – $20",
    description: "Irish-American gastropub with cozy atmosphere",
    website: "https://hudsonhoundnyc.com/"
  },
  {
    id: 12,
    name: "61 Grove Street",
    neighborhood: "west_village",
    subNeighborhood: "West Village",
    address: "61 Grove Street, NY 10014",
    location: [40.7332, -74.0025],
    days: ["monday", "tuesday", "wednesday", "thursday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "Pilsner/Cider/Beers – $6, House Wine/Aperol Spritz/Margarita/Sangria – $10, Bar snacks $6-$14",
    description: "Neighborhood tavern with craft beers and comfort food",
    website: "https://61grovestreet.com/"
  },
  {
    id: 13,
    name: "Dante",
    neighborhood: "west_village",
    subNeighborhood: "Greenwich Village",
    address: "79-81 Macdougal Street, NY 10012",
    location: [40.7286, -74.0015],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "3:00 PM - 5:00 PM",
    deals: "$10 Specials on select menu items",
    description: "Award-winning historic cafe known for Negronis and Italian fare",
    website: "https://dante-nyc.com/"
  },
  {
    id: 14,
    name: "Bobo",
    neighborhood: "west_village",
    subNeighborhood: "West Village",
    address: "181 W 10th St, NY 10014",
    location: [40.7350, -74.0026],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "5:00 PM - 7:00 PM",
    deals: "Oysters – $2 each, Wines – $8, Cocktails – $10, Beer – $5",
    description: "Romantic French restaurant in a townhouse setting",
    website: "https://bobonyc.com/"
  },
  {
    id: 15,
    name: "Down the Hatch",
    neighborhood: "west_village",
    subNeighborhood: "West Village",
    address: "179 W 4th St, NY 10014",
    location: [40.7323, -74.0021],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "Open - 7:00 PM",
    deals: "1/2 Off Entire Bar, $5 Jell-O Shots, $5 Michelob Ultra",
    description: "Underground sports bar with award-winning buffalo wings",
    website: "https://downthehatchnyc.com/"
  },
  {
    id: 16,
    name: "Boucherie West Village",
    neighborhood: "west_village",
    subNeighborhood: "West Village",
    address: "99 7th Avenue South, NY 10014",
    location: [40.7334, -74.0029],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "2:00 PM - 7:00 PM",
    deals: "Beer – $9, House Wine – $12, Cocktails – $14, Absinthe – $12, $17 Half Dozen Oysters",
    description: "French steakhouse with Belle Époque ambiance",
    website: "https://boucherieus.com/location/boucherie-west-village/"
  },
  {
    id: 17,
    name: "LELABAR",
    neighborhood: "west_village",
    subNeighborhood: "West Village",
    address: "75 Washington Pl, NY 10011",
    location: [40.7307, -73.9997],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Open - 6:00 PM",
    deals: "Wine – $12/glass, $44/bottle, Beer – $6, Cheese and Charcuterie – $5 each, Oysters – $3 each",
    description: "Intimate wine bar with curved counters and curated selection",
    website: "https://lelabar.com/"
  },
  {
    id: 18,
    name: "Due West",
    neighborhood: "west_village",
    subNeighborhood: "West Village",
    address: "189 W 10th St, NY 10014",
    location: [40.7348, -74.0031],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "Draft Cocktails – $10-11, Wine – $7, Beer – $5-6, Oysters – $1.50 each (min 6), Bar snacks $6-13",
    description: "Contemporary American bar with stylish interior",
    website: "https://duewestnyc.com/"
  },
  
  // Lower East Side
  {
    id: 19,
    name: "Loreley Beer Garden",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "7 Rivington St, New York, NY 10002",
    location: [40.7208, -73.9913],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$2 off draft beer, $16 one-liter steins, $12 beer flights, $2 off glasses of wine",
    description: "German-style beer garden with outdoor space",
    website: "https://www.loreleynyc.com/"
  },
  {
    id: 20,
    name: "Bar Belly",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "14 Orchard St, New York, NY 10002",
    location: [40.7167, -73.9906],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$1 happy hour oysters",
    description: "Sleek cocktail lounge with live music and seafood",
    website: "https://www.barbellynyc.com/"
  },
  {
    id: 21,
    name: "Jadis",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "42 Rivington St, New York, NY 10002",
    location: [40.7204, -73.9916],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "Wines starting at $7, shareable dishes under $10",
    description: "Cozy wine bar with brick walls and intimate atmosphere",
    website: "http://jadisnyc.com/"
  },
  {
    id: 22,
    name: "Bonnie Vee",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "17 Stanton St, New York, NY 10002",
    location: [40.7222, -73.9926],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$11 mimosas, martinis, gimlets, $10 house wines, shareable appetizers",
    description: "Cocktail bar with backyard garden and vintage decor",
    website: "https://www.bonnievee.com/"
  },
  {
    id: 23,
    name: "The Magician",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "118 Rivington St, New York, NY 10002",
    location: [40.7192, -73.9880],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "Select well liquor, draft beer, and wines for $6 each",
    description: "No-frills neighborhood bar with casual vibe",
    website: "https://www.themagicianbar.com/"
  },
  {
    id: 24,
    name: "Nurse Bettie",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "106 Norfolk St, New York, NY 10002",
    location: [40.7192, -73.9866],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$6 well drinks and beer, $8 cucumber vodka soda, constant specials",
    description: "Pinup-themed cocktail bar with burlesque shows",
    website: "https://nursebettie.com/"
  },
  {
    id: 25,
    name: "Essex",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "124 Rivington St, New York, NY 10002",
    location: [40.7192, -73.9872],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$8 signature cocktails, beer, wine, and sangria for less, snacks under $10",
    description: "Contemporary restaurant in historic market building",
    website: "https://www.essexnyc.com/"
  },
  {
    id: 26,
    name: "Verlaine",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "110 Rivington St, NY, NY 10002",
    location: [40.7195, -73.9898],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "5:00 PM - 10:00 PM",
    deals: "Lychee martini for $8, limited drink selection",
    description: "Sleek lounge with Southeast Asian inspired drinks and food",
    website: "https://www.verlainenyc.com/"
  },
  {
    id: 27,
    name: "The Ten Bells",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "247 Broome St, New York, NY 10002",
    location: [40.7184, -73.9911],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$1.50 oysters, $20 carafes of wine (about 16 oz)",
    description: "Rustic wine bar with tapas and natural wines",
    website: "https://tenbellsnyc.com/newwebsite/"
  },
  
  // East Village
  {
    id: 28,
    name: "Death & Company",
    neighborhood: "east_village",
    subNeighborhood: "East Village",
    address: "433 E 6th St, NY 10009",
    location: [40.7260, -73.9847],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "By reservation only",
    deals: "Happy hour not specified",
    description: "Pioneering speakeasy-style cocktail bar with expert mixology",
    website: "https://www.deathandcompany.com/"
  },
  {
    id: 29,
    name: "The Wayland",
    neighborhood: "east_village",
    subNeighborhood: "East Village",
    address: "700 E 9th St, NY 10009",
    location: [40.7261, -73.9784],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$1 oysters; discounted select beers, wines, cocktails",
    description: "Rustic neighborhood cocktail bar with live music",
    website: "https://www.thewaylandnyc.com/"
  },
  {
    id: 30,
    name: "The Gray Mare",
    neighborhood: "east_village",
    subNeighborhood: "East Village",
    address: "61 2nd Ave, NY 10003",
    location: [40.7256, -73.9889],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 draft beers; $8 cocktails, wines by the glass",
    description: "Neighborhood sports bar with craft beer selection",
    website: "https://thegraymarenyc.com/"
  },
  {
    id: 31,
    name: "Keybar",
    neighborhood: "east_village",
    subNeighborhood: "East Village",
    address: "432 E 13th St, NY 10009",
    location: [40.7300, -73.9798],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "4:00 PM - 10:00 PM",
    deals: "$4 bottles, shots; $5 drafts, well drinks; $6 wines; $7 margaritas",
    description: "High-energy nightlife spot with DJ and dancing",
    website: "http://www.keybar.com/"
  },
  {
    id: 32,
    name: "A10 Kitchen",
    neighborhood: "east_village",
    subNeighborhood: "East Village",
    address: "162 Avenue A, NY 10009",
    location: [40.7278, -73.9824],
    days: ["tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$13 burgers; $9 chicken wings; pitchers: margarita $21, mojito $23, sangria $30; select cocktails $7–$9",
    description: "Asian fusion restaurant with eclectic menu and vibrant atmosphere",
    website: "https://www.a10kitchen.com/"
  },
  {
    id: 33,
    name: "Upstate Craft Beer",
    neighborhood: "east_village",
    subNeighborhood: "East Village",
    address: "95 1st Ave, NY 10003",
    location: [40.7267, -73.9864],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "5:00 PM - 7:00 PM",
    deals: "$12 for 6 oysters and a beer",
    description: "Intimate seafood and craft beer restaurant with fresh oysters",
    website: "http://www.upstatenyc.com/"
  },
  {
    id: 34,
    name: "Bibi Wine Bar",
    neighborhood: "east_village",
    subNeighborhood: "East Village",
    address: "211 E 4th St, NY 10009",
    location: [40.7251, -73.9844],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Until 8:00 PM",
    deals: "$8 glasses, $28 bottles of select wines",
    description: "Intimate wine bar focused on natural and organic wines",
    website: "http://www.bibiwinebar.com/"
  },
  {
    id: 35,
    name: "Tile Bar (WCOU Radio)",
    neighborhood: "east_village",
    subNeighborhood: "East Village",
    address: "115 1st Ave, NY 10003",
    location: [40.7273, -73.9861],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "5:00 PM - 8:00 PM",
    deals: "$4 well drinks; $3 Bud, Bud Light drafts",
    description: "Historic dive bar in former radio station building",
    website: ""
  },
  
  // Chelsea
  {
    id: 36,
    name: "The Mermaid Inn",
    neighborhood: "chelsea",
    subNeighborhood: "Chelsea",
    address: "227 10th Ave, New York, NY 10011",
    location: [40.7466, -74.0035],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "4:30 PM - 6:30 PM",
    deals: "$1.25 oysters (min 6), $10 salmon tartar, $4 mini fish tacos, $12 fried calamari, $6 beer, $10 cocktails and wine",
    description: "New England-style seafood restaurant with nautical decor",
    website: "https://www.themermaidnyc.com/the-mermaid-inn-chelsea/"
  },
  {
    id: 37,
    name: "Porchlight",
    neighborhood: "chelsea",
    subNeighborhood: "Chelsea",
    address: "271 11th Ave, New York, NY 10001",
    location: [40.7509, -74.0045],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "3:00 PM - 7:00 PM",
    deals: "$11 select cocktails, $6 beer, $5 flasks of punch, $12 collard greens cheese dip, $12 popcorn",
    description: "Southern-inspired cocktail bar with hospitality and whiskey focus",
    website: "https://www.porchlightbar.com/"
  },
  {
    id: 38,
    name: "Fonda",
    neighborhood: "chelsea",
    subNeighborhood: "Chelsea",
    address: "189 9th Ave, New York, NY 10011",
    location: [40.7443, -74.0024],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "4:00 PM - 6:00 PM",
    deals: "$11 appetizers, $7-12 alcoholic beverages, $12 mezcalita",
    description: "Contemporary Mexican restaurant from Chef Roberto Santibañez",
    website: "https://fondarestaurant.com/"
  },
  {
    id: 39,
    name: "The Orchard Townhouse",
    neighborhood: "chelsea",
    subNeighborhood: "Chelsea",
    address: "242 10th Ave, New York, NY 10001",
    location: [40.7480, -74.0042],
    days: ["tuesday", "wednesday", "thursday", "friday"],
    hours: "3:00 PM - 6:00 PM",
    deals: "$10 cocktails, sharable appetizers",
    description: "Elegant neighborhood bistro with British influences",
    website: "https://www.theorchardtownhouse.com/"
  },
  {
    id: 40,
    name: "Cull & Pistol",
    neighborhood: "chelsea",
    subNeighborhood: "Chelsea",
    address: "75 9th Ave, New York, NY 10011",
    location: [40.7422, -74.0048],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 6:00 PM",
    deals: "Half-priced oysters (no cocktails or light bites)",
    description: "Seafood restaurant and oyster bar in Chelsea Market",
    website: "https://www.cullandpistol.com/"
  },
  {
    id: 41,
    name: "The Chelsea Bell",
    neighborhood: "chelsea",
    subNeighborhood: "Chelsea",
    address: "316 8th Ave, New York, NY 10001",
    location: [40.7474, -73.9991],
    days: ["monday", "tuesday", "wednesday", "thursday"],
    hours: "12:00 PM - 7:00 PM",
    deals: "$6 bottled domestic brews, $7 select drafts, $7 cocktails, $9 wine, $11 appetizers",
    description: "Sports bar with American pub fare and lively atmosphere",
    website: "https://www.thechelseabell.com/"
  },
  {
    id: 42,
    name: "The Copper Still",
    neighborhood: "chelsea",
    subNeighborhood: "Chelsea",
    address: "206 7th Ave, New York, NY 10011",
    location: [40.7434, -73.9970],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "12:00 PM - 6:00 PM",
    deals: "$10 cocktails, $6 draft beers, under $6 for fries, sliders, popcorn",
    description: "Cozy Irish pub with whiskey selection and comfort food",
    website: "https://www.thecopperstillnyc.com/"
  },
  {
    id: 43,
    name: "Bocca di Bacco",
    neighborhood: "chelsea",
    subNeighborhood: "Chelsea",
    address: "169 9th Ave, New York, NY 10011",
    location: [40.7432, -74.0020],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beer, $8 wine, $10 cocktails, $1.50 oysters, meatballs",
    description: "Upscale Italian restaurant with extensive wine list",
    website: "https://www.boccadibacconyc.com/"
  },
  
  // Upper East Side
  {
    id: 44,
    name: "The Penrose",
    neighborhood: "upper_east_side",
    subNeighborhood: "Upper East Side",
    address: "1590 2nd Ave, New York, NY 10028",
    location: [40.7740, -73.9495],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "3:00 PM - 7:00 PM",
    deals: "$2 off beer, wine, and well drinks",
    description: "Hip gastropub with rustic decor and craft beer selection",
    website: "https://www.penrosebar.com/reservations-1/"
  },
  {
    id: 45,
    name: "Pil Pil",
    neighborhood: "upper_east_side",
    subNeighborhood: "Upper East Side",
    address: "265 E 78th St, New York, NY 10075",
    location: [40.7736, -73.9557],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "Happy Hour Weekdays",
    deals: "$6-$8 drinks, small bites menu (e.g., Croquetas De Espinaca, Patatas Bravas)",
    description: "Spanish tapas and wine bar with warm ambiance",
    website: ""
  },
  {
    id: 46,
    name: "The Sefton",
    neighborhood: "upper_east_side",
    subNeighborhood: "Upper East Side",
    address: "1373 1st Ave, New York, NY 10021",
    location: [40.7683, -73.9545],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "11:00 AM - 7:00 PM",
    deals: "$5 domestic bottles, $9 margaritas",
    description: "Irish pub with sports and traditional pub fare",
    website: ""
  },
  {
    id: 47,
    name: "The Jeffrey Craft Beer & Bites",
    neighborhood: "upper_east_side",
    subNeighborhood: "Upper East Side",
    address: "311 E 60th St, New York, NY 10022",
    location: [40.7608, -73.9628],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$1 oysters, $6 draft beers, $10 cocktails, $2 off house wines",
    description: "Industrial-chic craft beer bar with espresso cafe and outdoor space",
    website: ""
  },
  {
    id: 48,
    name: "Five Mile Stone",
    neighborhood: "upper_east_side",
    subNeighborhood: "Upper East Side",
    address: "1640 2nd Ave, New York, NY 10028",
    location: [40.7771, -73.9492],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Happy Hour Daily",
    deals: "$7/pint for 24 rotating craft brews, $8 wine and well drinks, $7 select appetizers",
    description: "Upscale sports bar with American comfort food",
    website: ""
  },
  {
    id: 49,
    name: "The Stumble Inn",
    neighborhood: "upper_east_side",
    subNeighborhood: "Upper East Side",
    address: "1454 2nd Ave, New York, NY 10075",
    location: [40.7705, -73.9530],
    days: ["monday", "tuesday", "wednesday", "thursday"],
    hours: "Open to 4:00 PM",
    deals: "Half off entire bar, Regular happy hour: $5 Drafts, $6 Vodka Seltzers, $3 Budweiser, Bud Light, & Bud Light Seltzer Cans",
    description: "Lively sports bar with beer pong and casual American fare",
    website: ""
  },
  {
    id: 50,
    name: "The Pony Bar",
    neighborhood: "upper_east_side",
    subNeighborhood: "Upper East Side",
    address: "1444 1st Ave, New York, NY 10021",
    location: [40.7701, -73.9541],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "Starting at 4:20 PM",
    deals: "$7 draft beer, well drinks, and wine; All day Mon: $2 tacos, discounted drinks",
    description: "American craft beer bar with rotating taps and rustic decor",
    website: ""
  }
];