// New venues to add to our happy hour dataset
const newVenues = [
  // West Village
  {
    id: 102,
    name: "The Blind Tiger",
    neighborhood: "west_village",
    subNeighborhood: "West Village",
    address: "281 Bleecker St, NY 10014",
    location: [40.7313, -74.0031],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$1 off craft beers, $7 wines, $8 cocktails",
    description: "Renowned craft beer bar with extensive rotating tap selection",
    website: "https://blindtigeralehouse.com/"
  },
  {
    id: 103,
    name: "The Four-Faced Liar",
    neighborhood: "west_village",
    subNeighborhood: "West Village",
    address: "165 W 4th St, NY 10014",
    location: [40.7318, -74.0025],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $6 well drinks, $7 wines",
    description: "Cozy Irish pub with literary theme and authentic atmosphere",
    website: "https://thefourfacedliar.com/"
  },
  {
    id: 104,
    name: "The Half Pint",
    neighborhood: "west_village",
    subNeighborhood: "West Village",
    address: "76 W 3rd St, NY 10012",
    location: [40.7306, -74.0012],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "3:00 PM - 7:00 PM",
    deals: "$5 Espresso Martini/Aperol Spritz/Frozen Irish Coffee, $8 well drinks, $8 wine, $6 beer",
    description: "Casual pub with extensive beer selection and comfort food",
    website: "https://thehalfpint.com/"
  },
  {
    id: 105,
    name: "Greenwich Treehouse",
    neighborhood: "west_village",
    subNeighborhood: "West Village",
    address: "46 Greenwich Ave, NY 10011",
    location: [40.7352, -74.0008],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "sunday"],
    hours: "5:00 PM - 8:00 PM",
    deals: "$1 off beer/wine/well drinks, $5 Jell-O shot, $8 beer and shot",
    description: "Relaxed neighborhood bar with rustic decor and outdoor seating",
    website: "https://www.greenwichtreehouse.com/"
  },
  
  // East Village
  {
    id: 106,
    name: "The Lions Bar & Grill",
    neighborhood: "east_village",
    subNeighborhood: "East Village",
    address: "132 1st Ave, NY 10009",
    location: [40.7272, -73.9862],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 6:00 PM",
    deals: "$14 martini, $18 martini & fries, $8 margarita, $5 select beer, $7 Guinness",
    description: "Casual sports bar with great drink specials and pub fare",
    website: "https://www.thelionsbar.com/"
  },
  {
    id: 107,
    name: "The Scratcher",
    neighborhood: "east_village",
    subNeighborhood: "East Village",
    address: "209 E 5th St, NY 10003",
    location: [40.7267, -73.9865],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Authentic Irish pub with basement setting and live music",
    website: "https://thescratchernyc.com/"
  },
  
  // Midtown
  {
    id: 108,
    name: "The Irish Times",
    neighborhood: "midtown",
    subNeighborhood: "Midtown",
    address: "254 W 31st St, NY 10001",
    location: [40.7499, -73.9936],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Authentic Irish pub near Penn Station with great beer selection",
    website: "https://theirishtimesnyc.com/"
  },
  {
    id: 109,
    name: "The Bar at Times Square",
    neighborhood: "midtown",
    subNeighborhood: "Times Square",
    address: "255 W 43rd St, NY 10036",
    location: [40.7576, -73.9876],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Lively bar with dueling pianos and great drink specials",
    website: ""
  },
  {
    id: 110,
    name: "The Liberty",
    neighborhood: "midtown",
    subNeighborhood: "Midtown",
    address: "29 W 35th St, NY 10001",
    location: [40.7497, -73.9850],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Upscale gastropub with craft beer and creative American cuisine",
    website: "https://thelibertynyc.com/"
  },
  {
    id: 111,
    name: "RPM Underground",
    neighborhood: "midtown",
    subNeighborhood: "Times Square",
    address: "246 W 54th St, NY 10019",
    location: [40.7644, -73.9840],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "1:00 PM - 7:00 PM",
    deals: "50% off everything",
    description: "Rock 'n' roll themed bar with retro vibes and vinyl records",
    website: "https://rpmunderground.us/"
  },
  
  // Chelsea
  {
    id: 112,
    name: "Crown Alley",
    neighborhood: "chelsea",
    subNeighborhood: "Chelsea",
    address: "263 W 19th St, NY 10011",
    location: [40.7428, -73.9991],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beer, $8 wine, $8 cocktails, $2.50 oysters (min 6)",
    description: "Cozy neighborhood bar with craft cocktails and Irish influence",
    website: "https://crownalleynyc.com/"
  },
  {
    id: 113,
    name: "Bar Veloce",
    neighborhood: "chelsea",
    subNeighborhood: "Chelsea",
    address: "176 7th Ave, NY 10011",
    location: [40.7432, -73.9982],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "5:00 PM - 7:00 PM",
    deals: "$7 prosecco, rosato, red wine",
    description: "Sleek Italian wine bar with panini and small plates",
    website: "https://winebarveloce.com/"
  },
  {
    id: 114,
    name: "The Orchard Townhouse",
    neighborhood: "chelsea",
    subNeighborhood: "Chelsea",
    address: "242 10th Ave, NY 10001",
    location: [40.7494, -74.0032],
    days: ["tuesday", "wednesday", "thursday", "friday"],
    hours: "3:00 PM - 6:00 PM",
    deals: "$10 cocktails, sharable appetizers",
    description: "Elegant British-inspired townhouse with garden and refined cocktails",
    website: "https://theorchardtownhouse.com/"
  },
  {
    id: 115,
    name: "The Joyce Public House",
    neighborhood: "chelsea",
    subNeighborhood: "Chelsea",
    address: "315 W 39th St, NY 10018",
    location: [40.7568, -73.9939],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Irish pub with literary inspiration and comfort food",
    website: "https://thejoycepublichouse.com/"
  },
  {
    id: 116,
    name: "The Half King",
    neighborhood: "chelsea",
    subNeighborhood: "Chelsea",
    address: "505 W 23rd St, NY 10011",
    location: [40.7487, -74.0048],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 drafts, $7 wines, $8 cocktails",
    description: "Literary hangout founded by writers with regular readings and events",
    website: "https://thehalfking.com/"
  },
  
  // Lower East Side
  {
    id: 117,
    name: "169 Bar",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "169 E Broadway, NY 10002",
    location: [40.7142, -73.9900],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "2:00 PM - 7:00 PM",
    deals: "$2 off liquor drinks (except well shots), $1 off any beer",
    description: "Eclectic dive bar with leopard print pool table and tropical ambiance",
    website: "https://169barnyc.com/"
  },
  {
    id: 118,
    name: "The Bowery Beer Garden",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "93 Bowery, NY 10002",
    location: [40.7176, -73.9941],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Spacious outdoor beer garden with global pub fare",
    website: "https://bowerybeergarden.com/"
  },
  {
    id: 119,
    name: "The Delancey",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "168 Delancey St, NY 10002",
    location: [40.7178, -73.9864],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Multi-level venue with rooftop garden and live music",
    website: "https://thedelanceynyc.com/"
  },
  {
    id: 120,
    name: "The Skinny Bar & Lounge",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "174 Orchard St, NY 10002",
    location: [40.7209, -73.9881],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Narrow bar with DJs, dancing, and lively atmosphere",
    website: "https://theskinnybar.com/"
  },
  {
    id: 121,
    name: "The DL",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "95 Delancey St, NY 10002",
    location: [40.7183, -73.9878],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Multi-level venue with rooftop lounge and nightclub",
    website: "https://thedl-nyc.com/"
  },
  {
    id: 122,
    name: "The Back Room",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "102 Norfolk St, NY 10002",
    location: [40.7190, -73.9868],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "5:00 PM - 7:00 PM",
    deals: "$8 cocktails, $6 beers, $7 wines",
    description: "Authentic prohibition-era speakeasy with vintage decor",
    website: "https://backroomnyc.com/"
  },
  {
    id: 123,
    name: "Attaboy",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "134 Eldridge St, NY 10002",
    location: [40.7192, -73.9910],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "5:00 PM - 7:00 PM",
    deals: "$10 select cocktails, $6 beers",
    description: "Intimate speakeasy with bespoke cocktails and no menu",
    website: "https://attaboy.us/"
  },
  {
    id: 124,
    name: "The Slipper Room",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "167 Orchard St, NY 10002",
    location: [40.7208, -73.9883],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Burlesque theater and cocktail lounge with vintage vibes",
    website: "https://slipperroom.com/"
  },
  {
    id: 125,
    name: "Las' Lap",
    neighborhood: "lower_east_side",
    subNeighborhood: "Lower East Side",
    address: "74 Orchard St, NY 10002",
    location: [40.7171, -73.9913],
    days: ["monday", "tuesday", "wednesday", "thursday"],
    hours: "5:00 PM - 8:00 PM",
    deals: "$6 beer, $9 wine, $13 cocktails",
    description: "Caribbean-inspired cocktail bar with tropical drinks",
    website: ""
  },
  
  // Williamsburg
  {
    id: 126,
    name: "Fan Fried Rice Bar",
    neighborhood: "williamsburg",
    subNeighborhood: "Williamsburg",
    address: "92 S 6th St, Brooklyn, NY 11249",
    location: [40.7118, -73.9674],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "Until 6:00 PM",
    deals: "$7 draft pilsner, $8 sake, $10 wines, $12 specialty cocktails",
    description: "Taiwan-inspired eatery serving creative fried rice dishes",
    website: ""
  },
  {
    id: 127,
    name: "Cozy Royale",
    neighborhood: "williamsburg",
    subNeighborhood: "Williamsburg",
    address: "434 Humboldt St, Brooklyn, NY 11211",
    location: [40.7177, -73.9481],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "5:00 PM - 7:00 PM",
    deals: "$10 smash burger with fries, $10 martini",
    description: "Neighborhood restaurant from The Meat Hook team with butcher-focused menu",
    website: "https://www.cozyroyale.com/"
  },
  {
    id: 128,
    name: "The Exley",
    neighborhood: "williamsburg",
    subNeighborhood: "Williamsburg",
    address: "1 Jackson St, Brooklyn, NY 11211",
    location: [40.7164, -73.9678],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Intimate cocktail bar in a former auto repair shop",
    website: "https://theexley.com/"
  },
  {
    id: 129,
    name: "The Gibson",
    neighborhood: "williamsburg",
    subNeighborhood: "Williamsburg",
    address: "108 Bedford Ave, Brooklyn, NY 11249",
    location: [40.7197, -73.9569],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Cozy neighborhood bar with craft cocktails and vintage ambiance",
    website: "https://thegibsonbar.com/"
  },
  {
    id: 130,
    name: "The Counting Room",
    neighborhood: "williamsburg",
    subNeighborhood: "Williamsburg",
    address: "44 Berry St, Brooklyn, NY 11249",
    location: [40.7190, -73.9612],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Two-level bar with wine cellar and cocktail lounge",
    website: "https://thecountingroombk.com/"
  },
  
  // SoHo
  {
    id: 131,
    name: "Beyond The Pale",
    neighborhood: "soho",
    subNeighborhood: "SoHo",
    address: "53 Spring St, NY 10012",
    location: [40.7218, -73.9970],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:30 PM - 7:00 PM",
    deals: "$10 cocktails, $8 wine, $6 beer",
    description: "Irish-inspired bar with craft cocktails and stylish interior",
    website: "https://beyondthepalenyc.com/"
  },
  {
    id: 132,
    name: "The Crosby Bar",
    neighborhood: "soho",
    subNeighborhood: "SoHo",
    address: "79 Crosby St, NY 10012",
    location: [40.7226, -73.9985],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$10 house cocktails, $8 wine, $7 beers",
    description: "Sophisticated hotel bar with British influence and modern design",
    website: "https://crosbyhotel.com/"
  },
  {
    id: 133,
    name: "Pegu Club",
    neighborhood: "soho",
    subNeighborhood: "SoHo",
    address: "77 W Houston St, NY 10012",
    location: [40.7268, -74.0002],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "5:00 PM - 7:00 PM",
    deals: "$9 classic cocktails, $8 beer, $6 bar snacks",
    description: "Influential cocktail bar with colonial Burma-inspired decor",
    website: "https://peguclub.com/"
  },
  {
    id: 134,
    name: "Jimmy SoHo",
    neighborhood: "soho",
    subNeighborhood: "SoHo",
    address: "15 Thompson St, NY 10013",
    location: [40.7242, -74.0036],
    days: ["monday", "tuesday", "wednesday", "thursday"],
    hours: "4:00 PM - 6:00 PM",
    deals: "$12 specialty cocktails, $9 wine, $7 beer",
    description: "Rooftop cocktail bar with stunning city views",
    website: "https://jimmysoho.com/"
  },
  {
    id: 135,
    name: "Little Prince",
    neighborhood: "soho",
    subNeighborhood: "SoHo",
    address: "199 Prince St, NY 10012",
    location: [40.7261, -74.0011],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$9 cocktails, $8 wine, $6 beer, $5 oysters",
    description: "French bistro with literary theme and intimate atmosphere",
    website: "https://littleprincenyc.com/"
  },
  {
    id: 136,
    name: "The Ship",
    neighborhood: "soho",
    subNeighborhood: "SoHo",
    address: "158 Lafayette St, NY 10013",
    location: [40.7205, -73.9988],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "5:00 PM - 7:00 PM",
    deals: "$8 beer, $9 wine, $11 cocktails",
    description: "Nautical-themed cocktail bar with subterranean space",
    website: "https://theshipnyc.com/"
  },
  {
    id: 137,
    name: "City Winery",
    neighborhood: "soho",
    subNeighborhood: "SoHo",
    address: "155 Varick St, NY 10013",
    location: [40.7263, -74.0055],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 6:00 PM",
    deals: "$7 house wine, $5 beer, discounted small plates",
    description: "Urban winery, restaurant, and music venue with house-made wines",
    website: "https://citywinery.com/"
  },
  {
    id: 138,
    name: "Lola Taverna",
    neighborhood: "soho",
    subNeighborhood: "SoHo",
    address: "210 6th Ave, NY 10014",
    location: [40.7282, -74.0008],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "3:00 PM - 6:00 PM",
    deals: "$10 cocktails, $8 wine, $6 beer",
    description: "Greek taverna with Mediterranean menu and lively atmosphere",
    website: "https://lolatavernanyc.com/"
  },
  {
    id: 139,
    name: "The Woo",
    neighborhood: "soho",
    subNeighborhood: "SoHo",
    address: "206 Spring St, NY 10012",
    location: [40.7259, -74.0032],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 6:00 PM",
    deals: "$7 cocktails, $5 beers, $6 wines",
    description: "Korean-inspired restaurant with craft cocktails",
    website: "https://thewoonyc.com/"
  },
  {
    id: 140,
    name: "The Spring Lounge",
    neighborhood: "soho",
    subNeighborhood: "SoHo",
    address: "48 Spring St, NY 10012",
    location: [40.7216, -73.9963],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Historic dive bar with shark-themed decor and beer focus",
    website: "https://thespringlounge.com/"
  },
  {
    id: 141,
    name: "The Mulberry",
    neighborhood: "soho",
    subNeighborhood: "Little Italy",
    address: "76 Mulberry St, NY 10013",
    location: [40.7170, -73.9975],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Italian-American bar and restaurant with classic fare",
    website: ""
  },
  
  // Harlem
  {
    id: 142,
    name: "The Honey Well",
    neighborhood: "harlem",
    subNeighborhood: "Harlem",
    address: "3604 Broadway, NY 10031",
    location: [40.8330, -73.9465],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Basement cocktail lounge with 70s decor and vinyl records",
    website: "https://thehoneywellnyc.com/"
  },
  {
    id: 143,
    name: "The Edge Harlem",
    neighborhood: "harlem",
    subNeighborhood: "Harlem",
    address: "101 Edgecombe Ave, NY 10030",
    location: [40.8081, -73.9471],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$7 cocktails, $5 beers, $6 wines",
    description: "Caribbean-influenced restaurant with warm aesthetic",
    website: "https://theedgeharlem.com/"
  },
  {
    id: 144,
    name: "Lolo's Seafood Shack",
    neighborhood: "harlem",
    subNeighborhood: "Harlem",
    address: "303 W 116th St, NY 10026",
    location: [40.8044, -73.9551],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Caribbean-New England seafood fusion in colorful beachside setting",
    website: "https://lolosseafoodshack.com/"
  },
  {
    id: 145,
    name: "The Grange Bar & Eatery",
    neighborhood: "harlem",
    subNeighborhood: "Harlem",
    address: "1635 Amsterdam Ave, NY 10031",
    location: [40.8261, -73.9455],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Farm-to-table restaurant with craft cocktails and rustic setting",
    website: "https://thegrangenyc.com/"
  },
  {
    id: 146,
    name: "Harlem Hops",
    neighborhood: "harlem",
    subNeighborhood: "Harlem",
    address: "2268 Adam Clayton Powell Jr Blvd, NY 10030",
    location: [40.8107, -73.9478],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 craft beers, $8 wines",
    description: "Black-owned craft beer bar focusing on small, independent breweries",
    website: "https://harlemhops.com/"
  },
  {
    id: 147,
    name: "Harlem Tavern",
    neighborhood: "harlem",
    subNeighborhood: "Harlem",
    address: "2153 Frederick Douglass Blvd, NY 10026",
    location: [40.8028, -73.9549],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$8 select red & white wine, $9 sangria, $7 house mixed drinks",
    description: "Spacious beer garden with outdoor seating and live music",
    website: "https://harlemtavern.com/"
  },
  {
    id: 148,
    name: "67 Orange Street",
    neighborhood: "harlem",
    subNeighborhood: "Harlem",
    address: "2130 Frederick Douglass Blvd, NY 10026",
    location: [40.8025, -73.9551],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "5:00 PM - 7:00 PM",
    deals: "$12 cocktails, $8 beer, $12 glasses of wine, $40 bottles",
    description: "Craft cocktail speakeasy named after historic Almack's dance hall",
    website: "https://67orangestreet.com/"
  },
  
  // Financial District
  {
    id: 149,
    name: "The Growler",
    neighborhood: "financial_district",
    subNeighborhood: "Financial District",
    address: "55 Stone St, NY 10004",
    location: [40.7043, -74.0103],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Historic Stone Street pub with extensive craft beer selection",
    website: "https://thegrowlernyc.com/"
  },
  {
    id: 150,
    name: "The Black Hound",
    neighborhood: "financial_district",
    subNeighborhood: "Financial District",
    address: "301 South End Ave, NY 10280",
    location: [40.7113, -74.0168],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Craft cocktail lounge with upscale ambiance and small plates",
    website: "https://blackhoundny.com/"
  },
  {
    id: 151,
    name: "The Beekman Pub",
    neighborhood: "financial_district",
    subNeighborhood: "Financial District",
    address: "15 Beekman St, NY 10038",
    location: [40.7110, -74.0078],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Classic New York pub with historic character",
    website: "https://beekmanpub.com/"
  },
  {
    id: 152,
    name: "The Paris Cafe",
    neighborhood: "financial_district",
    subNeighborhood: "South Street Seaport",
    address: "119 South St, NY 10038",
    location: [40.7060, -74.0021],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Historic waterfront tavern dating back to 1873",
    website: "https://pariscafenyc.com/"
  },
  {
    id: 153,
    name: "The Stone Street Tavern",
    neighborhood: "financial_district",
    subNeighborhood: "Financial District",
    address: "52 Stone St, NY 10004",
    location: [40.7039, -74.0101],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 drafts, $7 wines, $8 cocktails",
    description: "Colonial-era cobblestone street location with outdoor seating",
    website: "https://stonestreettavernnyc.com/"
  },
  
  // Greenpoint
  {
    id: 154,
    name: "Sereneco",
    neighborhood: "greenpoint",
    subNeighborhood: "Greenpoint",
    address: "113 Franklin St, Brooklyn, NY 11222",
    location: [40.7301, -73.9586],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$10 cocktails, $5-6 beers, $2 oysters",
    description: "Airy restaurant in historic Pencil Factory with seasonal cuisine",
    website: "https://sereneconyc.com/"
  },
  {
    id: 155,
    name: "The Pencil Factory",
    neighborhood: "greenpoint",
    subNeighborhood: "Greenpoint",
    address: "142 Franklin St, Brooklyn, NY 11222",
    location: [40.7310, -73.9582],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Historic bar in former pencil factory with old-school vibe",
    website: "https://pencilfactorybar.com/"
  },
  {
    id: 156,
    name: "Elder Greene",
    neighborhood: "greenpoint",
    subNeighborhood: "Greenpoint",
    address: "160 Franklin St, Brooklyn, NY 11222",
    location: [40.7315, -73.9577],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Cozy cocktail bar with vintage vibe and elegant drinks",
    website: "https://eldergreene.com/"
  },
  {
    id: 157,
    name: "Threes Brewing",
    neighborhood: "greenpoint",
    subNeighborhood: "Greenpoint",
    address: "113 Franklin St, Brooklyn, NY 11222",
    location: [40.7301, -73.9586],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Local brewery with experimental beers and food collaborations",
    website: "https://threesbrewing.com/"
  },
  {
    id: 158,
    name: "Brooklyn Winery",
    neighborhood: "greenpoint",
    subNeighborhood: "Greenpoint",
    address: "61 Guernsey St, Brooklyn, NY 11222",
    location: [40.7249, -73.9534],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Urban winery with rustic chic decor and small-batch wines",
    website: "https://brooklynwinery.com/"
  },
  
  // Bushwick
  {
    id: 159,
    name: "The Keep",
    neighborhood: "bushwick",
    subNeighborhood: "Bushwick",
    address: "205 Cypress Ave, Brooklyn, NY 11237",
    location: [40.7046, -73.9143],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Medieval-themed bar with absinthe focus and dark ambiance",
    website: "https://thekeepbk.com/"
  },
  {
    id: 160,
    name: "The Wheelhouse",
    neighborhood: "bushwick",
    subNeighborhood: "Bushwick",
    address: "165 Wilson Ave, Brooklyn, NY 11237",
    location: [40.7011, -73.9277],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Neighborhood bar with bicycle theme and casual atmosphere",
    website: "https://wheelhousebk.com/"
  },
  {
    id: 161,
    name: "The Evergreen",
    neighborhood: "bushwick",
    subNeighborhood: "Bushwick",
    address: "1281 Myrtle Ave, Brooklyn, NY 11221",
    location: [40.7000, -73.9302],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Plant-filled cocktail bar with garden party atmosphere",
    website: "https://theevergreenbk.com/"
  },
  {
    id: 162,
    name: "The Bad Old Days",
    neighborhood: "bushwick",
    subNeighborhood: "Ridgewood",
    address: "1684 Woodbine St, Brooklyn, NY 11237",
    location: [40.7060, -73.9066],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Cozy neighborhood bar with vintage furniture and board games",
    website: ""
  },
  {
    id: 163,
    name: "The Bodega",
    neighborhood: "bushwick",
    subNeighborhood: "Bushwick",
    address: "1402 St Nicholas Ave, Brooklyn, NY 11237",
    location: [40.7062, -73.9106],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Latinx-owned bar with convenience store theme and deli sandwiches",
    website: ""
  },
  
  // Park Slope
  {
    id: 164,
    name: "The Double Windsor",
    neighborhood: "park_slope",
    subNeighborhood: "Park Slope",
    address: "210 Prospect Park West, Brooklyn, NY 11215",
    location: [40.6620, -73.9798],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Craft beer bar with great burgers and casual vibe",
    website: "https://doublewindsorbk.com/"
  },
  {
    id: 165,
    name: "Blueprint",
    neighborhood: "park_slope",
    subNeighborhood: "Park Slope",
    address: "196 5th Ave, Brooklyn, NY 11217",
    location: [40.6778, -73.9799],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Intimate cocktail bar with extensive wine list and small plates",
    website: "https://blueprintbrooklyn.com/"
  },
  {
    id: 166,
    name: "The Commissioner",
    neighborhood: "park_slope",
    subNeighborhood: "Park Slope",
    address: "247 5th Ave, Brooklyn, NY 11215",
    location: [40.6770, -73.9819],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Cocktail bar and restaurant with Irish whiskey focus",
    website: "https://thecommissionerbrooklyn.com/"
  },
  {
    id: 167,
    name: "Freddy's Bar",
    neighborhood: "park_slope",
    subNeighborhood: "South Slope",
    address: "627 5th Ave, Brooklyn, NY 11215",
    location: [40.6647, -73.9884],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Historic dive bar with live music and quirky atmosphere",
    website: "https://freddysbar.com/"
  },
  {
    id: 168,
    name: "High Dive",
    neighborhood: "park_slope",
    subNeighborhood: "Park Slope",
    address: "243 5th Ave, Brooklyn, NY 11215",
    location: [40.6773, -73.9818],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Relaxed bar with free popcorn, pinball, and jukebox",
    website: "https://highdivebrooklyn.com/"
  },
  {
    id: 169,
    name: "Fonda",
    neighborhood: "park_slope",
    subNeighborhood: "Park Slope",
    address: "431 7th Ave, Brooklyn, NY 11215",
    location: [40.6663, -73.9847],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "5:00 PM - 7:00 PM",
    deals: "$7 classic margaritas, $6 draft beer, $8 wine",
    description: "Chef Roberto Santibañez's upscale Mexican restaurant",
    website: "https://fondarestaurant.com/"
  },
  {
    id: 170,
    name: "Bar Basic",
    neighborhood: "park_slope",
    subNeighborhood: "Park Slope",
    address: "504 5th Ave, Brooklyn, NY 11215",
    location: [40.6684, -73.9863],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "12:00 PM - 7:00 PM",
    deals: "$4 draft beers, $5 well drinks, $6 wine",
    description: "No-frills neighborhood bar with wallet-friendly happy hour",
    website: ""
  },
  {
    id: 171,
    name: "Hugo & Sons",
    neighborhood: "park_slope",
    subNeighborhood: "Park Slope",
    address: "367 7th Ave, Brooklyn, NY 11215",
    location: [40.6681, -73.9839],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "3:00 PM - 6:00 PM",
    deals: "$6 draft beer, $8 wine, $8 well drinks",
    description: "Italian-American restaurant with warm, homey atmosphere",
    website: "https://www.hugoandsons.com/"
  },
  {
    id: 172,
    name: "Korzo",
    neighborhood: "park_slope",
    subNeighborhood: "Park Slope",
    address: "667 5th Ave, Brooklyn, NY 11215",
    location: [40.6639, -73.9889],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 Slovakian draft beers, $7 wine, $7 well drinks",
    description: "Central European restaurant known for fried-burger specialty",
    website: "https://www.korzobrooklyn.com/"
  },
  {
    id: 173,
    name: "Pasta Louise",
    neighborhood: "park_slope",
    subNeighborhood: "Park Slope",
    address: "803 8th Ave, Brooklyn, NY 11215",
    location: [40.6586, -73.9871],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 6:00 PM",
    deals: "$6 draft beer, $8 wine, $8 select cocktails",
    description: "Family-friendly Italian restaurant with handmade pasta",
    website: "https://www.pastalouise.com/"
  },
  
  // Upper East Side
  {
    id: 174,
    name: "The Stumble Inn",
    neighborhood: "upper_east_side",
    subNeighborhood: "Upper East Side",
    address: "1454 2nd Ave, NY 10021",
    location: [40.7699, -73.9554],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "Open - 7:00 PM",
    deals: "Half off everything",
    description: "Fun sports bar with games and extensive draft beer selection",
    website: ""
  },
  
  // Upper West Side
  {
    id: 175,
    name: "Jake's Dilemma",
    neighborhood: "upper_west_side",
    subNeighborhood: "Upper West Side",
    address: "430 Amsterdam Ave, NY 10024",
    location: [40.7851, -73.9778],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "3:00 PM - 7:00 PM",
    deals: "Half off entire bar, with some exclusions",
    description: "Lively sports bar with arcade games and casual atmosphere",
    website: "https://www.jakesdilemmanyc.com/"
  },
  
  // NoMad
  {
    id: 176,
    name: "Hillstone",
    neighborhood: "nomad",
    subNeighborhood: "NoMad",
    address: "378 Park Ave S, NY 10010",
    location: [40.7429, -73.9841],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 6:00 PM",
    deals: "$8 cocktails, $6 beers, $7 wines",
    description: "Upscale American restaurant chain with consistent quality",
    website: "https://hillstonerestaurant.com/"
  },
  {
    id: 177,
    name: "The Playwright",
    neighborhood: "nomad",
    subNeighborhood: "NoMad",
    address: "27 W 35th St, NY 10001",
    location: [40.7500, -73.9852],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beers, $7 wines, $8 cocktails",
    description: "Irish pub with theater district vibe and traditional fare",
    website: "https://playwrighttavern.com/"
  },
  {
    id: 178,
    name: "The Cannibal",
    neighborhood: "nomad",
    subNeighborhood: "NoMad",
    address: "113 E 29th St, NY 10016",
    location: [40.7435, -73.9827],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beers, $8 wines, $10 cocktails",
    description: "Butcher shop and restaurant focusing on meat dishes and craft beer",
    website: "https://thecannibalnyc.com/"
  },
  {
    id: 179,
    name: "Tavern 29",
    neighborhood: "nomad",
    subNeighborhood: "NoMad",
    address: "47 E 29th St, NY 10016",
    location: [40.7440, -73.9848],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$7 beer, $8 wine, $9 select cocktails",
    description: "Three-story gastropub with rooftop beer garden",
    website: ""
  },
  
  // Kips Bay
  {
    id: 180,
    name: "Tara Rose",
    neighborhood: "kips_bay",
    subNeighborhood: "Kips Bay",
    address: "384 3rd Ave, NY 10016",
    location: [40.7415, -73.9805],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$7 cocktails, 2-for-14 bites, BOGO apps",
    description: "Modern Irish pub with cocktail focus and upscale atmosphere",
    website: "https://tararosenyc.com/"
  },
  {
    id: 181,
    name: "Sundays Well",
    neighborhood: "kips_bay",
    subNeighborhood: "Kips Bay",
    address: "360 3rd Ave, NY 10016",
    location: [40.7410, -73.9806],
    days: ["sunday"],
    hours: "All Day",
    deals: "$10 specialty drinks, $10 burger, $1 oysters",
    description: "Irish-owned neighborhood bar with game screenings",
    website: "http://www.sundayswellnyc.com/"
  },
  {
    id: 182,
    name: "The Gem Saloon",
    neighborhood: "kips_bay",
    subNeighborhood: "Kips Bay",
    address: "375 3rd Ave, NY 10016",
    location: [40.7414, -73.9803],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$8 wine, $5 beer, half-price drinks",
    description: "Western-themed bar with craft cocktails and vintage decor",
    website: "http://www.thegemsaloonnyc.com/"
  },
  {
    id: 183,
    name: "Bella Union",
    neighborhood: "kips_bay",
    subNeighborhood: "Kips Bay",
    address: "411 3rd Ave, NY 10016",
    location: [40.7426, -73.9790],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "Check website for current specials",
    description: "Italian-American restaurant with welcoming atmosphere",
    website: "http://www.bellaunionnyc.com/"
  },
  {
    id: 184,
    name: "Ernie O'Malley's",
    neighborhood: "kips_bay",
    subNeighborhood: "Kips Bay",
    address: "140 E 27th St, NY 10016",
    location: [40.7426, -73.9821],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "Until 7:00 PM",
    deals: "Good beer selection for drafts and cans",
    description: "Traditional Irish pub with historical namesake",
    website: "https://www.ernieomalleys.com/"
  },
  {
    id: 185,
    name: "Dog & Bone Tavern",
    neighborhood: "kips_bay",
    subNeighborhood: "Kips Bay",
    address: "3rd Ave, NY 10016",
    location: [40.7417, -73.9805],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "Check venue for current specials",
    description: "British-style pub with traditional fare and ales",
    website: ""
  },
  
  // Murray Hill
  {
    id: 186,
    name: "Albion",
    neighborhood: "murray_hill",
    subNeighborhood: "Murray Hill",
    address: "575 2nd Ave, NY 10016",
    location: [40.7452, -73.9772],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "3:00 PM - 7:00 PM",
    deals: "$6 beer, $7 wine, $9 cocktails",
    description: "British-inspired gastropub with craft beer and quality pub fare",
    website: "http://albionnyc.com/"
  },
  {
    id: 187,
    name: "The Junction",
    neighborhood: "murray_hill",
    subNeighborhood: "Murray Hill",
    address: "329 Lexington Ave, NY 10016",
    location: [40.7463, -73.9793],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$6 beer, $7 wine, $8 well drinks",
    description: "Casual neighborhood bar with sports screen and friendly staff",
    website: "http://thejunctionnyc.com/"
  },
  {
    id: 188,
    name: "Park Avenue Tavern",
    neighborhood: "murray_hill",
    subNeighborhood: "Murray Hill",
    address: "99 Park Ave, NY 10016",
    location: [40.7488, -73.9798],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "3:00 PM - 6:00 PM",
    deals: "$8 signature cocktails, $7 wine, $6 beer",
    description: "Elegant tavern with self-serve beer taps and speakeasy basement",
    website: "http://parkavenuetavernnyc.com/"
  },
  {
    id: 189,
    name: "Slattery's Midtown Pub",
    neighborhood: "murray_hill",
    subNeighborhood: "Murray Hill",
    address: "8 E 36th St, NY 10016",
    location: [40.7496, -73.9819],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$5 beer, $6 wine, $8 well drinks",
    description: "Classic Irish pub with sports screens and traditional menu",
    website: "http://slatterysmidtownpub.com/"
  },
  {
    id: 190,
    name: "La Cava Wine Bar",
    neighborhood: "murray_hill",
    subNeighborhood: "Murray Hill",
    address: "939 2nd Ave, NY 10022",
    location: [40.7539, -73.9684],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 7:00 PM",
    deals: "$8 glasses of wine, $7 beer, discounted charcuterie",
    description: "Cozy wine bar with Spanish and Italian influences",
    website: "http://lacavany.com/"
  },
  {
    id: 191,
    name: "Murray Hill Local",
    neighborhood: "murray_hill",
    subNeighborhood: "Murray Hill",
    address: "539 3rd Ave, NY 10016",
    location: [40.7481, -73.9775],
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    hours: "4:00 PM - 8:00 PM",
    deals: "$6 beer, $7 wine, $8 cocktails",
    description: "Neighborhood bar with rustic charm and friendly service",
    website: "http://murrayhilllocal.com/"
  },
  
  // Ethyl's Alcohol & Food - special case, Upper East Side location
  {
    id: 192,
    name: "Ethyl's Alcohol & Food",
    neighborhood: "upper_east_side",
    subNeighborhood: "Upper East Side",
    address: "1629 2nd Ave, NY 10028",
    location: [40.7774, -73.9512],
    days: ["tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
    hours: "5:00 PM - 7:00 PM",
    deals: "$5 beer, $6 wine, $10 select cocktails",
    description: "70s-themed bar with go-go dancers and retro atmosphere",
    website: ""
  }
];

// Export the new venues data
module.exports = newVenues;